### ISSUE TITLE
Create docker to simplify deploy

### ISSUE THREAD

**Issue by viniarruda** [viniarruda/graphql-elixir#1]
We need create an integration with CI to deploy this application in production.

**Comment by RafaelGSS** [comment]
Automatic deploy is hard because doesn't have information about where is to deploy or the keys to deploy. What do you think about changing the name to dockerized the application to be able to deploy yourself?

**Comment by viniarruda** [comment]
> Automatic deploy is hard because doesn't have information about where is to deploy or the keys to deploy. What do you think about changing the name to dockerized the application to be able to deploy yourself?

I agree. Good idea
